package apperror

func ThrowError(err error) {
	panic(err)
}
